import { merge } from "../helpers"
import Collection from "../collection"

// Generated by CoffeeScript 1.7.1
export default function(name, options) {
  var propOptions;
  if (options == null) {
    options = {};
  }
  propOptions = merge(options, {
    changed: true,
    get: function() {
      var valueName;
      valueName = "_" + name;
      if (!this[valueName]) {
        this[valueName] = new Collection([]);
        this[valueName].change.bind(this[name + "_property"].trigger);
      }
      return this[valueName];
    },
    set: function(value) {
      return this[name].update(value);
    }
  });
  this.property(name, propOptions);
  return this.property(name + 'Count', {
    get: function() {
      return this[name].length;
    },
    dependsOn: name
  });
};
