// Generated by CoffeeScript 1.7.1
(function() {
  var Compile;

  Compile = {
    element: function(ast, context) {
      return Serenade.renderView(ast, context);
    },
    view: function(ast, context) {
      if (ast.bound) {
        return new BoundViewView(ast, context);
      } else {
        return Serenade.templates[ast.argument].render(context).view;
      }
    },
    text: function(ast, context) {
      return new TextView(ast, context);
    },
    collection: function(ast, context) {
      return new CollectionView(ast, context);
    },
    "in": function(ast, context) {
      return new InView(ast, context);
    },
    "if": function(ast, context) {
      return new IfView(ast, context);
    },
    unless: function(ast, context) {
      return new UnlessView(ast, context);
    }
  };

}).call(this);
